const translations = {
            en: {
                site_title: "Ready Scratch Code for TurboWarp",
                settings_button: "Settings",
                filter_label: "Show:",
                filter_all: "All",
                filter_favorites: "Favorites",
                sort_label: "Sort:",
                sort_new: "New",
                sort_old: "Old",
                sort_random: "Randomly",
                search_placeholder: "Search...",
                tea_button: "Buy me a coffee, please ☕",
                no_favorites: "No favorite cards yet...",
                settings_title: "Settings",
                language_label: "Site Language:",
                theme_label: "Site Theme:",
                theme_system: "System Mode",
                theme_light: "Light Mode",
                theme_dark: "Dark Mode",
                hashtags_label: "Hashtags:",
                toggle_hashtags_show: "Show Hashtags",
                toggle_hashtags_hide: "Hide Hashtags",
                download_button: "Download",
                docs_button: "Detailed",
                author_prefix: "<b>Author:</b><br>",
                date_prefix: "———<br><b>Created (day.month.year):</b><br>",
                new_badge: "New"
             },
            ru: {
                site_title: "Готовый Scratch-код для TurboWarp",
                settings_button: "Настройки",
                filter_label: "Показать:",
                filter_all: "Все",
                filter_favorites: "Избранные",
                sort_label: "Сортировка:",
                sort_new: "Новые",
                sort_old: "Старые",
                sort_random: "Случайно",
                search_placeholder: "Поиск...",
                tea_button: "Купите мне пирожок, пожалуйста 😋",
                no_favorites: "Пока нет избранных плашек...",
                settings_title: "Настройки",
                language_label: "Язык сайта:",
                theme_label: "Тема сайта:",
                theme_system: "Системный режим",
                theme_light: "Светлый режим",
                theme_dark: "Тёмный режим",
                hashtags_label: "Хештеги:",
                toggle_hashtags_show: "Показать Хештеги",
                toggle_hashtags_hide: "Скрыть Хештеги",
                download_button: "Скачать",
                docs_button: "Подробнее",
                author_prefix: "<b>Автор:</b><br>",
                date_prefix: "———<br><b>Создано (день.месяц.год):</b><br>",
                new_badge: "Новое"
            }
         };